services:
  - type: web
    name: pos-system
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    autoDeploy: true
    branch: main
    repo: https://github.com/atShopifyDevGuy/POS
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: pos-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 365d
      - key: CLOUD_SERVER_URL
        value: https://your-cloud-server.com/api
      - key: CLOUD_API_KEY
        value: your_cloud_api_key

databases:
  - name: pos-database
    plan: free
